"use client"

import { useState } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Download, Share, FileText, Mail, Check, Copy } from "lucide-react"

export function ExportShare() {
  const [isExporting, setIsExporting] = useState(false)
  const [emailCopied, setEmailCopied] = useState(false)

  const handleExport = () => {
    setIsExporting(true)
    setTimeout(() => {
      setIsExporting(false)
      alert("📄 Report exported successfully! Your therapist-friendly PDF is ready.")
    }, 2500)
  }

  const copyEmailSummary = () => {
    const emailContent = `Hi [Therapist Name],

I hope this email finds you well. I've been using MindMirror to track my emotional wellness, and I wanted to share some insights from this week:

MOOD SUMMARY:
• Overall mood trend: Stable with positive momentum
• Most challenging day: Tuesday (anxiety level 7/10)
• Best day: Friday (happiness level 8/10)
• Primary emotions: Anxious (40%), Happy (35%), Neutral (25%)

COPING STRATEGIES USED:
• 4-7-8 breathing technique (3x this week)
• Mindful walking (daily)
• Gratitude journaling (4x this week)

INSIGHTS:
This week I noticed that my anxiety tends to peak on Tuesdays, possibly related to work stress. The coping techniques have been helpful, especially the breathing exercises.

I'd love to discuss these patterns in our next session.

Best regards,
[Your Name]

Generated by MindMirror - Mental Wellness Tracker`

    navigator.clipboard.writeText(emailContent)
    setEmailCopied(true)
    setTimeout(() => setEmailCopied(false), 2000)
  }

  return (
    <div className="space-y-6">
      <Card className="rounded-2xl shadow-md border border-gray-200 bg-white">
        <CardHeader>
          <CardTitle className="text-lg font-semibold text-gray-800 flex items-center gap-2">
            <FileText className="w-5 h-5 text-indigo-500" />📋 Professional Report
          </CardTitle>
          <p className="text-sm text-gray-500">Generate comprehensive reports for your healthcare provider</p>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="bg-gray-50 rounded-xl p-4">
            <h4 className="font-medium text-gray-800 mb-2">Your report includes:</h4>
            <ul className="text-sm text-gray-600 space-y-1">
              <li className="flex items-center gap-2">
                <div className="w-1.5 h-1.5 bg-indigo-500 rounded-full"></div>
                Weekly mood trends and patterns
              </li>
              <li className="flex items-center gap-2">
                <div className="w-1.5 h-1.5 bg-indigo-500 rounded-full"></div>
                Emotional intensity tracking
              </li>
              <li className="flex items-center gap-2">
                <div className="w-1.5 h-1.5 bg-indigo-500 rounded-full"></div>
                Coping strategies used and effectiveness
              </li>
              <li className="flex items-center gap-2">
                <div className="w-1.5 h-1.5 bg-indigo-500 rounded-full"></div>
                Personal insights and journal entries
              </li>
              <li className="flex items-center gap-2">
                <div className="w-1.5 h-1.5 bg-indigo-500 rounded-full"></div>
                Recommendations for continued care
              </li>
            </ul>
          </div>

          <Button
            onClick={handleExport}
            disabled={isExporting}
            className="w-full bg-indigo-500 hover:bg-indigo-600 text-white rounded-xl px-4 py-2 transition-all duration-200"
          >
            <Download className={`w-4 h-4 mr-2 ${isExporting ? "animate-bounce" : ""}`} />
            {isExporting ? "Generating PDF..." : "Download PDF Report"}
          </Button>
        </CardContent>
      </Card>

      <Card className="rounded-2xl shadow-md border border-gray-200 bg-white">
        <CardHeader>
          <CardTitle className="text-lg font-semibold text-gray-800 flex items-center gap-2">
            <Mail className="w-5 h-5 text-indigo-500" />📧 Email Summary
          </CardTitle>
          <p className="text-sm text-gray-500">Quick summary for your therapist or healthcare provider</p>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-sm text-gray-600">
            Generate a professional email summary that you can send directly to your therapist or counselor.
          </p>

          <Button
            onClick={copyEmailSummary}
            className="w-full bg-emerald-500 hover:bg-emerald-600 text-white rounded-xl px-4 py-2 transition-all duration-200"
          >
            {emailCopied ? (
              <>
                <Check className="w-4 h-4 mr-2" />
                Copied to Clipboard!
              </>
            ) : (
              <>
                <Copy className="w-4 h-4 mr-2" />
                Copy Therapist Email Summary
              </>
            )}
          </Button>

          {emailCopied && (
            <div className="text-xs text-emerald-600 bg-emerald-50 rounded-lg p-3">
              ✅ Email summary copied! You can now paste it into your email client and customize as needed.
            </div>
          )}
        </CardContent>
      </Card>

      <Card className="rounded-2xl shadow-md border border-gray-200 bg-white">
        <CardHeader>
          <CardTitle className="text-lg font-semibold text-gray-800 flex items-center gap-2">
            <Share className="w-5 h-5 text-indigo-500" />🔒 Privacy & Security
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="text-sm text-gray-600 space-y-2">
            <p>• All data is stored locally on your device</p>
            <p>• Reports are generated client-side for privacy</p>
            <p>• No personal information is sent to external servers</p>
            <p>• You control who receives your mental health data</p>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
